<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Eceni.Core.Base\Eceni.Core.Base.csproj" />
    <ProjectReference Include="..\..\src\Eceni.Core.Database.MySQL\Eceni.Core.Database.MySQL.csproj" />
    <ProjectReference Include="..\..\src\Eceni.Core.Secrets\Eceni.Core.Secrets.csproj" />
    <ProjectReference Include="..\..\src\Eceni.Core.Secrets.Aws\Eceni.Core.Secrets.Aws.csproj" />
    <ProjectReference Include="..\..\src\Eceni.Core.Secrets.Infisical\Eceni.Core.Secrets.Infisical.csproj" />
  </ItemGroup>

</Project>
